### ISSUE TITLE
Opens in separate Window without address bar but has icon in dock

### ISSUE THREAD

**Issue by ramonsmits** [eladnava/applicationize#7] opened 2016-02-27 10:53 UTC
I tried to make an application from `https://mail.google.com/mail/u/0/#inbox` and it shows up in the Chrome App Launcher.

![image](https://cloud.githubusercontent.com/assets/152998/13372552/08147016-dd48-11e5-9830-af4f18e38e4d.png)

However, opening does not make it visible in the application switcher or the Dock. It does open it in a separate window without an address bar.

Using Chrome:  49.0.2623.63 beta (64-bit)
OSX: 10.11.3 (15D21)

**Comment by eladnava** [comment] 2016-02-28 14:38
Hey @ramonsmits!
I tried to reproduce your issue but failed to do so.

I generated a .crx for Gmail via the URL you provided and installed it. Immediately upon opening it, it appeared in the Dock and in the Launchpad:

### Dock
![screen shot 2016-02-28 at 4 36 36 pm](https://cloud.githubusercontent.com/assets/4394189/13379814/7761c9b8-de39-11e5-9d51-ce23a3805127.png)

### Launchpad

![screen shot 2016-02-28 at 4 35 48 pm](https://cloud.githubusercontent.com/assets/4394189/13379815/776449b8-de39-11e5-91e3-9beae41ec468.png)

I'm on Chrome `48.0.2564.116 (64-bit)` (and it seems to be the latest version -- at least that's what I'm told by Chrome).

Do you see the app in the Launchpad at least?

**Comment by eladnava** [comment] 2016-03-16 21:53
Hi @ramonsmits,
I'm closing this for now, let me know if you still have trouble.

**Closed by eladnava** 2016-03-16 21:53 UTC
