### ISSUE TITLE
Use other extensions within Applicationize

### ISSUE THREAD

**Issue by greg-wolff** [eladnava/applicationize#59] opened 2017-09-05 21:19 UTC
Is there any way to use other chrome extensions (for example a visual skin extension: [ink for google](https://carlosjeurissen.com/ink-for-google)) within Applicationize?

**Comment by eladnava** [comment] 2017-09-07 16:47
Hi @greg-wolff,
This is a duplicate of #21. A workaround is mentioned in that issue.

**Closed by eladnava** 2017-09-07 16:47 UTC
