### ISSUE TITLE
Facebook messenger voice calls not working

### ISSUE THREAD

**Issue by heiba** [eladnava/applicationize#45] opened 2017-05-25 18:54 UTC
It's nice that you have facebook messenger appliczationized in the homepage of this git repository.

However for me, when calling anyone via the voice call feature, a blank pop-up would open and no call will actually be initiated - it the blank pop-up would just stay still.

This issue still happens even when I chose open links as an internal pop-up, and allowing microphone capture

**Comment by eladnava** [comment] 2017-06-02 05:42
Hi @heiba,
Thanks for the report.

I've reproduced the issue. This occurs because the link's `href` is `about:blank` and requires JavaScript to run in order for the page URL to be determined.

There is already an open issue for this: #36. I will close this and we can keep discussing there.

**Comment by eladnava** [comment] 2017-06-02 05:43
Hi @heiba,
Thanks for the report.

I've reproduced the issue. This occurs because the link's `href` is `about:blank` and requires JavaScript to run in order for the page URL to be determined.

There is already an open issue for this: #36. I will close this and we can keep discussing there.

For now, please try this workaround:

1) Go to the target website
2) Click the three vertical dots in the top right of Chrome
3) More Tools -> Add to Applications
4) Tick `Open as window`

**Closed by eladnava** 2017-06-02 05:42 UTC

**Comment by heiba** [comment] 2017-06-02 07:45
"Add to Applications' is not present in More Tools in Chrome on Mac
