### ISSUE TITLE
Google contacts in consumer Gmail doesn't open.

### ISSUE THREAD

**Issue by guidokok** [eladnava/applicationize#33] opened 2017-01-06 16:09 UTC
When it opens, it doesn't load google contacts and only shows an empty window.

**Comment by eladnava** [comment] 2017-01-06 16:16
Hi @guidokok,
Can you please post a screenshot and more detailed explanation?

Thanks!

**Comment by eladnava** [comment] 2017-02-21 20:30
Does that window show `about:blank` in the address bar? 

Looks like a duplicate of #36.

**Comment by guidokok** [comment] 2017-02-22 10:54
I think it's about:blank but I cannot verify as your app doesn't show the address bar.

**Comment by eladnava** [comment] 2017-06-02 12:39
Closing for now as this appears to be a duplicate of #36.

**Closed by eladnava** 2017-06-02 12:39 UTC
Labels: pending-hosted-app-migration
