### ISSUE TITLE
Stops working in 2018?

### ISSUE THREAD

**Issue by ChristoferKarlsson** [eladnava/applicationize#62] opened 2017-10-25 16:46 UTC
Sorry for writing this as an issue, but I found no other way to contact.

I really like this solution for creating local web apps, but I wonder if will continue working in the future or not. As far as I understand, Chrome for non-Chromebooks will stop support apps in early 2018. Is Applicationize affected by this? If so, can the problem be solved?

Source: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by eladnava** [comment] 2017-10-27 11:12
Hi @Christofer81,
Unfortunately, that appears to be the case. Chrome is removing support for the Packaged Apps feature which Applicationize relies on, in early 2018. 

We have yet to see whether loading Packaged Apps via `.crx` file will still work (or if this will only affect the Chrome Web Store apps). If not, then unfortunately, this project will become deprecated, and alternative solutions will be provided (such as using [Nativefier](https://github.com/jiahaog/nativefier) to create a similar experience, which I highly recommend).

**Comment by WojtekKruszewski** [comment] 2017-11-02 10:57
There's also http://www.bulldockbrowser.com and http://fluidapp.com. Both seem to be thin wrappers around Safari webview so generated "apps" weight only ~10MB.

**Comment by eladnava** [comment] 2017-11-03 00:48
These are also good alternatives, thanks for the mention! 👍 

When the Chrome team will finally deprecate Chrome apps, I'll list these alternatives in the README.

**Comment by vielhuber** [comment] 2018-04-04 20:14
This seems now be reality. I cannot even download the crx file anymore.

**Comment by eladnava** [comment] 2018-04-05 11:40
@vielhuber I can't reproduce, and it appears I am using the latest version of Chrome on OS X, version `65.0.3325.181`. Which are you using?

**Comment by vielhuber** [comment] 2018-04-05 23:00
False alarm, sorry. Now it works.

Hope that this really remains; Yesterday I tested a bunch of other tools (nativefier, fluidapp, bulldockbrowser, ...) and nothing got close to applicationize.

**Comment by eladnava** [comment] 2018-04-06 08:13
@vielhuber Awesome, great to hear 👍

**Comment by Trizam** [comment] 2018-04-22 18:44
Chrome won't let me download the package. To dangerous they say :(
I have no option to say: "I take the risk"

**Comment by eladnava** [comment] 2018-04-22 21:35
Hi @Trizam,
Still works for me.

What version of Google Chrome are you using? Are you on OS X? Which version of OS X? I just updated to the latest version of Chrome on OS X and I can still generate and download extensions from applicationize.me/now.

**Comment by Trizam** [comment] 2018-04-23 22:55
I updated my Chrome and it work !
Thx for this amazing app by the ways !!

**Comment by eladnava** [comment] 2018-04-27 02:39
Awesome!

**Comment by refactoredjello** [comment] 2018-05-11 20:12
I've been able to get this working natively on mac os using the new enable Desktop PWA flag. If anyone is interested google just announced this during google I/O, check this out: [PWA on desktop](https://developers.google.com/web/updates/2018/05/dpwa). Chrome extensions work within the window. Although you do have to go to chrome://apps and then right click on the app shortcut and select open as window.

**Comment by eladnava** [comment] 2018-05-12 16:10
@refactoredjello Doesn't this new feature require the target web app to publish a `manifest.json` and effectively be a Progressive Web App?

**Comment by refactoredjello** [comment] 2018-05-12 16:27
@eladnava For the general use case it does. But it also allows the user to force the creation of PWA via the add to desktop/applications chrome option. I believe even if the app doesn't use service workers it will still function. I've successfully turned Google inbox and keep into a windowed desktop app with chrome extensions working.

**Comment by eladnava** [comment] 2018-05-12 16:35
@refactoredjello Hmm, very interesting. There used to be a chrome flag called "The new bookmark app system" (`#disable-new-bookmark-apps`) which added this same option under the option icon -> More Tools -> Add to Applications.

It seems this flag has been removed/merged with "Desktop PWAs" (`#enable-desktop-pwas`) and now offers the same functionality under a different flag.

However, you do need to manually go into `chrome://apps`, right click the app you created, and select "Open as Window" for it to function independently.

Nice find!

**Comment by chr0max** [comment] 2018-06-29 10:10
How about using this with vivaldi?

**Comment by eladnava** [comment] 2018-07-01 01:39
@chr0max The Vivaldi browser is a completely different beast, but check this out:
https://forum.vivaldi.net/topic/15495/websites-as-desktop-apps

**Comment by ajays-in** [comment] 2018-07-11 17:52
Not working in Chromium 67 on Linux anymore when trying to create new app. Old apps still work though. Thanks. Was quite useful all these days

**Comment by eladnava** [comment] 2018-07-12 01:35
@ajays-in Please elaborate -- is it impossible to install the extension? Is no icon for the app created?

**Comment by ajays-in** [comment] 2018-07-21 19:30
Sorry for the late reply. After extension file created by applicationize is downloaded, dragging and dropping the file into chrome://extensions/ no longer installs the extension. Instead, Chrome simply offers to re-download the file back to local computer

**Comment by eladnava** [comment] 2018-07-22 06:43
@ajays-in Can you please let me know your Chrome browser version?

**Comment by eladnava** [comment] 2018-07-22 06:44
@ajays-in Any chance you can try Google Chrome on Linux to see if it's still there?

**Comment by ajays-in** [comment] 2018-07-26 03:49
@eladnava Extension is not installed on Google Chrome either. FYI Chrome About: Version 68.0.3440.75 (Official Build) (64-bit)

Could some default setting been changed by Google that can be flipped back?

**Comment by eladnava** [comment] 2018-07-26 13:15
Just updated my Chrome to the same version (`68.0.3440.75 (Official Build) (64-bit)`) but on OS X and was able to drag and drop an Applicationize-generated `.crx` extension into `chrome://extensions`.

Can you please try dragging and dropping the `.crx` from your Linux file browser into the `chrome://extensions` page and *not* from the Chrome download bar? That might be the cause.

**Comment by ajays-in** [comment] 2018-07-27 07:38
Dragging from File Manager makes no difference. Chrome / Chromium simply offers to re download the .crx file.

**Comment by eladnava** [comment] 2018-07-27 07:47
Ah, so it must be a Linux-only thing. They must have removed support for it on Linux. I don't have access to a Linux based machine to test though.

I highly recommend you check out Nativefier as an alternative to Applicationize:
https://github.com/jiahaog/nativefier

**Comment by ajays-in** [comment] 2018-07-27 07:52
Thanks for looking into this

**Comment by toddcavanaugh** [comment] 2018-07-31 13:50
I'm told Applicationize no longer works on Windows with updated version of Chrome. Is that true? Any expectations to make it work again?

**Comment by eladnava** [comment] 2018-07-31 15:10
@toddcavanaugh it appears to be affecting Linux only. Can you reproduce? I'm on OS X and have no access to a Windows PC.

**Comment by toddcavanaugh** [comment] 2018-07-31 15:16
@eladnava I'm on macOS only as well, but I've had 3 people tell me Windows isn't working. You can't drag an extension to install it anymore from my understanding on Windows. It does work on macOS.

**Comment by eladnava** [comment] 2018-08-01 02:25
@toddcavanaugh Well that's annoying.

I guess a workaround is for people to enable Developer Mode in `chrome://extensions/`, extract the `.crx`, and then use the "Load unpacked extension" function to load the extension.

But I can't find any reference on the Internet regarding the removal of this feature in the latest Chrome version.

**Comment by raneaniket** [comment] 2018-08-02 02:27
Applicationize no longer working in Mac either anymore.

Chrome Version 68.0.3440.84 (Official Build) (64-bit)
MacBook Pro (15-inch, 2017)
Mac Osx 10.13.6 (17G65)

**Comment by eladnava** [comment] 2018-08-02 02:45
@raneaniket @toddcavanaugh @ajays-in  

I think I found a workaround.

Simply enable Developer Mode in `chrome://extensions/` in the top right corner:
![screen shot 2018-08-02 at 10 44 09 am](https://user-images.githubusercontent.com/4394189/43559545-04a22c0c-9641-11e8-95eb-d0ce58a795e8.png)

You will then be able to drag and drop `.crx` files generated from Applicationize. Make sure to drop these in the from OS file browser and not from the Chrome downloads bar. :

**Comment by raneaniket** [comment] 2018-08-02 14:37
@eladnava : Thanks, that worked for me.

**Comment by toddcavanaugh** [comment] 2018-08-02 15:22
@eladnava and @raneaniket, can you confirm that worked on a PC? I was told it didn't but I'm wondering if the refresh the page was a missed step.

**Comment by ajays-in** [comment] 2018-08-02 15:28
Developer mode works on Linux / Chrome 68.0.3440.84. Developer mode can be switched off after extension is installed and installed extension will still continue to work.

@toddcavanaugh Had to restart Chrome after enabling Developer Mode before I could install the extension

**Comment by raneaniket** [comment] 2018-08-04 01:41
@toddcavanaugh : I do not use Applicationize with my chrome on windows 10. I have been using "create shortcut" option under tools to save websites as desktop apps.

**Comment by eladnava** [comment] 2018-08-05 07:47
@toddcavanaugh Unfortunately I do not have access to a Windows PC to confirm. However, as @raneaniket mentioned, you can use the "Create Shortcut" option under tools to generate a shortcut app almost identical to what Applicationize generates. This feature exists on Chrome for Windows only.

**Comment by ataiya** [comment] 2019-01-09 03:46
I confirm the fix above seems to work well:
https://github.com/eladnava/applicationize/issues/62#issuecomment-409788035

enable developer mode in extensions, refresh, and drag&drop from OSX/Finder.

**Comment by eladnava** [comment] 2019-10-27 14:07
Seems like we can still get Applicationize extensions to work with Developer Mode enabled. Closing this for now. 🎉

**Closed by eladnava** 2019-10-27 14:07 UTC
