### ISSUE TITLE
New window blank

### ISSUE THREAD

**Issue by dwy904** [eladnava/applicationize#49] opened 2017-06-28 23:16 UTC
I made a chrome shortcut app for my RStudio Server. When I clicked 'open in new window' button from the current app interface. It only shown a blank page and it just kept loading forever. I inspected it and found this error message. I am wondering if it's possible to resolve this.

**Uncaught TypeError: Cannot read property 'registerAsRStudioSatellite' of null
    at z9e (rstudio-1.js:1658:771)
    at y9e (rstudio-1.js:1138:27)
    at P9e (rstudio-1.js:1437:27)
    at koe.loe [as wj] (rstudio-1.js:1685:157567)
    at k7h.l7h [as Cq] (rstudio-24.js:3982:297861)
    at Gfd.Hfd [as vj] (rstudio-0.js:9462:7351)
    at yl (rstudio-0.js:8082:79)
    at nl (rstudio-0.js:6690:60)
    at Bl.Cl [as vj] (rstudio-0.js:9458:13920)
    at wl (rstudio-0.js:1386:25)**

**Comment by eladnava** [comment] 2017-06-29 05:30
This is a duplicate of #36. There appears to be no easy fix for this issue currently.

**Closed by eladnava** 2017-06-29 05:30 UTC

**Comment by eladnava** [comment] 2017-06-29 05:34
Possible workaround:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260
